Navbar
IsabellUrban/quiz-app pull request #3
Opened 2024-04-11 11:15 UTC by IsabellUrban

2024-04-11 11:51 UTC, Sannsfilm commented on index.html
> +            <a href="Home"></a>
Ich glaube, vor der Home kannst du #Home machen also mit #, wenn du da noch keine reference habe? cmiiw

2024-04-12 07:02 UTC, eneben requested changes
:-)

2024-04-12 07:02 UTC, eneben commented on index.html
> +            <a href="/bookmark.html"></a>
ich würde den Link machen mit ./name.html

2024-04-12 07:02 UTC, eneben commented on index.html
> +            <a href="#Home"></a>
hier würde ich auf ./index.html verweisen, damit es auch von den anderen seiten aus funktioniert

2024-04-12 07:02 UTC, eneben commented on index.html
> +            <a href="/profile.html"></a>
hier auch mit ./

2024-04-12 08:33 UTC, merged